#!/bin/bash
# 10.04.2024 svelue
# This is a game where you need to hit the number 20 while adding one ore two each round.

spielstand=1
while true; do

    # neuer Spieler-Versuch einlesen
    while true; do
        read -p "Ihre Versuch: " versuch
        if [[ $versuch -gt 20 ]]; then
            echo "Dein Versuch ist zu gross!"
        elif [[ $versuch -eq $(($spielstand+1)) ]] \
          || [[ $versuch -eq $(($spielstand +2)) ]]; then
            break
        else
            echo "Falscher Versuch, try again"
        fi
    done
    spielstand=$versuch
    if [[ $spielstand -eq 20 ]]; then
       echo "Wow, du hast gewonnen. Tolle Leistung!"
       exit 0
    fi


    # Computer ist am Zug
    if [[ $spielstand -gt 17 ]]; then
        spielstand=20
    else
        spielstand=$(($spielstand + $[RANDOM%2]+1))
    fi
    echo "Der Computer sagt $spielstand."
    if [[ $spielstand -eq 20 ]]; then
       echo "Computer gewann. Es wurde 20 genannt."
       exit 1
    fi
done
